### PR TITLE
Extensibility Enhancements

### PR DESCRIPTION
**Pull request by cornyhorse**
I have a couple of suggestions in this one to make it so that people can keep in sync with upstream changes.  This PR has a few other modifications to help with extensibility that I think will dovetail nicely with the changes you were talking about making with regards to styling.

- Moved navbar to a base.html page and inherited it in the other templates
- Added a context processor that dynamically displays the copyright, which can be added as a "TextAsset" in the SQLite database, so that it overwrites your default but only if it exists in the database. This allows the asset to be updated outside of the git workflow.  There are several other options that I included but didn't fully flesh out (such as an "about page") since I didn't want to go to far afield w/o feedback if it's something you want to do.
- Added a flag for posts that allows the user to overwrite the front page outside of the git workflow and store the index page in the SQLite database. If the "is_index_page" flag is toggled, it hides the page from search and displays the content on the front page.
- I added a method of dynamically indicated the CSRF_ALLOWED and ALLOWED_HOSTS from an environment variable, which is IMO a better way of handling this than my last PR
- I added a new "static-extensions" folder and added it to the .gitignore, but specified that it is a place to put assets that are neither user modified, nor part of the default codebase.  The idea here is that if this makes sense to you, the "TextAsset" class can take a path name for the logo and override the stock one and be able to stay in sync with upstream changes more easily.
-

### CODE REVIEW

**Comment by roderiano** [comment]
Perfect. It's been incredible sharing this work with you. At night I will create the PR and Issues templates for the repository. This way we can register suggestions and work with gitflow (dev > main). It will help in the merge conflict process.

Once again, I really appreciate your collaboration.

When you deploy the blog and want to share it with me, I would be happy.

**Comment by cornyhorse** [comment]
Just finished deploying! https://mattkingsbury.com/

**Comment by roderiano** [comment]
> Just finished deploying! https://mattkingsbury.com/

Very cool. What do you think of the idea of ​​having a preview of the author's profile? Like photo and description? I can put it on the roadmap to implement the feature.

**Comment by cornyhorse** [comment]
Actually, that would make a lot more sense. I'm kind of making the main page about me b/c I'm doing this as a kind of personal brand etc. etc. that happens to also be a blog but I could just as easily make the front page more generic and then have a section as someone who happens to be an author. 

You could even make it so that there's a blurb about someone and then associate a single media with them.   You can *almost* do it as is right now:

This is an example of the blog index:
      <h1>{{ special_post.title }}</h1>
        <div>{{ special_post.content|safe|markdownify }}</div>

If you had another model you could make it so that the markdonify thing accepts the media for the user, so it's easily to import the images and then do:

<div class="container">

        <div>{{ user_class.content|safe|markdownify }}</div>
        Image
    </div>

You'd just have to get the media from the database somehow

**Comment by roderiano** [comment]
@cornyhorse I merged your pull request and also added a .env parser that modifies the **SECRET_KEY, DEBUG, and ALLOWED_HOSTS** configurations. Please refer to the example in the env-sample file.

Additionally, I adjusted the contribution guide to provide clear instructions on addressing issues and directing pull requests to the dev branch before the main branch.

**Remember to save your SECRET_KEY for setting it in the .env file.**

**Pull request merged**
